### ISSUE TITLE
顶部价格每次点击会刷新

### ISSUE THREAD

**Issue by moondcr** [getdecred/forum#4]
不知道是不是 rails 里面的 turbolink 处理的问题。每次点击新的页面，顶部的价格会重新加载。希望达成的效果是顶部不重新渲染。这个问题如果比较好处理，先修改掉。

https://dcr66.com

**Comment by cheenwe** [comment]
刚看了, 需要好好研究下

**Comment by glebm** [comment]
You can simply give the div an `id` and add `data-turbolinks-permanent`: https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads

**Comment by moondcr** [comment]
@glebm thanks so much. that works perfect!  I had to suspended the forum temporarily due to some restrictions in China. Will reopen after I get permission from the (suck) government.

Plus, I'd really suggest you to follow [Decred](https://decred.org), its an awesome project. 😆
